[[messages]]
message = """
Hello there from test3
"""

# Wildcard files
[[files]]
source = "dot-foo-dir/*"
target = "$HOME/dot-foo-dir/*"
type = "link"

# [[files]]
# source = "dot-foo-dir/dot-foo-dir1.txt"
# target = "/dot-foo-dir/dot-foo-dir1.txt"
# type = "link"
