name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        export DATABASE_URL=sqlite://compile_db.sqlite
        cargo build --verbose
    - name: Run tests
      run: |
        export DATABASE_URL=sqlite://compile_db.sqlite
        cargo test --verbose
